app:
  aws:
    access_key_id: adfasdf
    secret_access_key: dfasdfas
  s3:
    bucket: asdfasdfasd
    region: us-east-1

jwt:
  token:
    secret: somereallycomplexsecret

allowed:
  cors:
    origins: http://localhost:4200,http://localhost:8090,http://amitthk.mywire.org:8091,*
  http:
    methods: HEAD,GET,POST,PUT,DELETE,PATCH,OPTIONS

spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/sb_s3_app
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-runs-millis: 1

datasource:
  flyway:
    url: jdbc:h2:file:~/sb_s3_app
    username: sa
    password:
    driver-class-name: org.h2.Driver


server:
  port: 8997